"""Transaction-owned digest persistence; application contains no SQL."""

from contextlib import AbstractAsyncContextManager
from datetime import datetime
from typing import Literal, Protocol
from uuid import UUID

from app.modules.identity.domain.auth import AuthenticatedActor

from ..domain.digests import DailySummarySnapshot, SummaryDelivery
from ..domain.schedules import DailySummarySchedule, ReportingWindow


class DigestRepository(Protocol):
    async def authenticate(self) -> None: ...
    async def authenticate_viewer(self) -> None: ...
    async def authorize(self, project_id: UUID) -> None: ...
    async def schedule_for_window(self, window_id: UUID) -> DailySummarySchedule: ...
    async def window(self, schedule: DailySummarySchedule, at: datetime) -> ReportingWindow: ...
    async def applied(
        self, schedule: DailySummarySchedule, version: int
    ) -> DailySummarySchedule: ...
    async def existing(self, window_id: UUID) -> DailySummarySnapshot | None: ...
    async def capture(
        self,
        schedule: DailySummarySchedule,
        window: ReportingWindow,
        at: datetime,
        reason: Literal["COVERAGE", "CUTOFF", "RESUME"],
    ) -> DailySummarySnapshot: ...
    async def create(self, snapshot: DailySummarySnapshot) -> None: ...
    async def claim(self, at: datetime, worker_id: str) -> UUID | None: ...
    async def complete_delivery(self, id: UUID, at: datetime, worker_id: str) -> None: ...
    async def fail_delivery(self, id: UUID, at: datetime, worker_id: str) -> None: ...
    async def feed(self) -> tuple[SummaryDelivery, ...]: ...


class DigestTransactionPort(Protocol):
    def __call__(
        self, actor: AuthenticatedActor
    ) -> AbstractAsyncContextManager[DigestRepository]: ...
