"""Typed persistence and transaction ports for configuration only."""

from contextlib import AbstractAsyncContextManager
from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.modules.identity.domain.auth import AuthenticatedActor

from ..domain.schedules import DailySummarySchedule, Reporter, ReportingWindow, ScheduleDraft


class ScheduleRepository(Protocol):
    async def authenticate(self) -> None: ...
    async def find_project(self, reference: str) -> UUID: ...
    async def authorize(self, project_id: UUID) -> None: ...
    async def recipients(self, project_id: UUID) -> tuple[Reporter, ...]: ...
    async def current(self, project_id: UUID) -> DailySummarySchedule | None: ...
    async def by_id(self, schedule_id: UUID) -> DailySummarySchedule: ...
    async def save(self, schedule: DailySummarySchedule) -> None: ...
    async def store_preview(self, draft: ScheduleDraft) -> None: ...
    async def preview_by_id(self, draft_id: UUID) -> ScheduleDraft: ...
    async def window(self, schedule: DailySummarySchedule, at: datetime) -> ReportingWindow: ...
    async def replay(
        self, operation: str, key: str, fingerprint: str
    ) -> dict[str, object] | None: ...
    async def remember(
        self, operation: str, key: str, fingerprint: str, result: dict[str, object]
    ) -> None: ...
    async def record_audit(
        self, action: str, key: str, resource_id: UUID | None, code: str | None = None
    ) -> None: ...


class ScheduleTransactionPort(Protocol):
    def __call__(
        self, actor: AuthenticatedActor
    ) -> AbstractAsyncContextManager[ScheduleRepository]: ...
