"""daily_summary_schedules

Revision ID: 0029
Revises: 0028
Create Date: 2026-10-04 13:36:10.835073
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0029"
down_revision: str | Sequence[str] | None = "0028"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automation_schedule_drafts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("owner_membership_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "owner_membership_id"],
            ["memberships.organization_id", "memberships.id"],
            name=op.f(
                "fk_automation_schedule_drafts_organization_id_owner_membership_id_memberships"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "project_id"],
            ["projects.organization_id", "projects.id"],
            name=op.f("fk_automation_schedule_drafts_organization_id_project_id_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_schedule_drafts")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_automation_schedule_drafts_organization_id_id")
        ),
    )
    op.create_index(
        "ix_schedule_draft_expiry",
        "automation_schedule_drafts",
        ["organization_id", "expires_at"],
        unique=False,
    )
    op.create_table(
        "automation_schedules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "project_id"],
            ["projects.organization_id", "projects.id"],
            name=op.f("fk_automation_schedules_organization_id_project_id_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_schedules")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_automation_schedules_organization_id_id")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "project_id",
            name=op.f("uq_automation_schedules_organization_id_project_id"),
        ),
    )
    op.create_table(
        "automation_schedule_versions",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "schedule_id"],
            ["automation_schedules.organization_id", "automation_schedules.id"],
            name=op.f(
                "fk_automation_schedule_versions_organization_id_schedule_id_automation_schedules"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "organization_id",
            "schedule_id",
            "version",
            name=op.f("pk_automation_schedule_versions"),
        ),
    )
    op.create_index(
        "ix_schedule_version_effective",
        "automation_schedule_versions",
        ["organization_id", "schedule_id", "effective_at", "version"],
        unique=False,
    )
    op.create_table(
        "automation_schedule_recipients",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "membership_id"],
            ["memberships.organization_id", "memberships.id"],
            name=op.f(
                "fk_automation_schedule_recipients_organization_id_membership_id_memberships"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "schedule_id", "version"],
            [
                "automation_schedule_versions.organization_id",
                "automation_schedule_versions.schedule_id",
                "automation_schedule_versions.version",
            ],
            name=op.f(
                "fk_automation_schedule_recipients_organization_id_schedule_id_version_automation_schedule_versions"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "organization_id",
            "schedule_id",
            "version",
            "membership_id",
            name=op.f("pk_automation_schedule_recipients"),
        ),
    )
    op.create_table(
        "reporting_windows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("applied_version", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "schedule_id", "applied_version"],
            [
                "automation_schedule_versions.organization_id",
                "automation_schedule_versions.schedule_id",
                "automation_schedule_versions.version",
            ],
            name=op.f(
                "fk_reporting_windows_organization_id_schedule_id_applied_version_automation_schedule_versions"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reporting_windows")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_reporting_windows_organization_id_id")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "schedule_id",
            "starts_at",
            name=op.f("uq_reporting_windows_organization_id_schedule_id_starts_at"),
        ),
    )
    op.create_index(
        "ix_reporting_window_lookup",
        "reporting_windows",
        ["organization_id", "schedule_id", "starts_at", "ends_at"],
        unique=False,
    )
    op.create_table(
        "reporting_window_reporters",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("window_id", sa.Uuid(), nullable=False),
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "membership_id"],
            ["memberships.organization_id", "memberships.id"],
            name=op.f("fk_reporting_window_reporters_organization_id_membership_id_memberships"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "window_id"],
            ["reporting_windows.organization_id", "reporting_windows.id"],
            name=op.f("fk_reporting_window_reporters_organization_id_window_id_reporting_windows"),
        ),
        sa.PrimaryKeyConstraint(
            "organization_id",
            "window_id",
            "membership_id",
            name=op.f("pk_reporting_window_reporters"),
        ),
    )
    # ### end Alembic commands ###

    for table in (
        "automation_schedules",
        "automation_schedule_versions",
        "automation_schedule_recipients",
        "automation_schedule_drafts",
        "reporting_windows",
        "reporting_window_reporters",
    ):
        predicate = (
            "organization_id=nullif(current_setting('app.organization_id',true),'')::uuid "
            "AND EXISTS(SELECT 1 FROM memberships m JOIN users u ON u.id=m.user_id "
            f"WHERE m.organization_id={table}.organization_id "
            "AND m.id=nullif(current_setting('app.membership_id',true),'')::uuid "
            "AND m.role IN ('MANAGER','ADMIN') AND m.is_active AND u.is_active)"
        )
        if table == "automation_schedule_drafts":
            predicate += (
                " AND owner_membership_id="
                "nullif(current_setting('app.membership_id',true),'')::uuid"
            )
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY schedule_scope ON {table} TO app_runtime "
            f"USING ({predicate}) WITH CHECK ({predicate})"
        )
        mutable = table == "automation_schedules"
        grant = "SELECT,INSERT,UPDATE" if mutable else "SELECT,INSERT"
        op.execute(f"GRANT {grant} ON {table} TO app_runtime")
        if not mutable:
            op.execute(
                f"CREATE TRIGGER schedule_fact_immutable BEFORE UPDATE OR DELETE ON {table} "
                "FOR EACH ROW EXECUTE FUNCTION guard_daily_reporting_fact()"
            )


def downgrade() -> None:
    """Reverse the schema change when the revision supports it."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reporting_window_reporters")
    op.drop_index("ix_reporting_window_lookup", table_name="reporting_windows")
    op.drop_table("reporting_windows")
    op.drop_table("automation_schedule_recipients")
    op.drop_index("ix_schedule_version_effective", table_name="automation_schedule_versions")
    op.drop_table("automation_schedule_versions")
    op.drop_table("automation_schedules")
    op.drop_index("ix_schedule_draft_expiry", table_name="automation_schedule_drafts")
    op.drop_table("automation_schedule_drafts")
    # ### end Alembic commands ###
