"""reporting_scope_history

Revision ID: 0030
Revises: 0029
Create Date: 2026-10-04 13:51:11.288055
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0030"
down_revision: str | Sequence[str] | None = "0029"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automation_task_scope_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("assignee_membership_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("reporter_active", sa.Boolean(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "assignee_membership_id"],
            ["memberships.organization_id", "memberships.id"],
            name=op.f(
                "fk_automation_task_scope_history_organization_id_assignee_membership_id_memberships"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "task_id"],
            ["tasks.organization_id", "tasks.id"],
            name=op.f("fk_automation_task_scope_history_organization_id_task_id_tasks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_task_scope_history")),
        sa.UniqueConstraint(
            "organization_id",
            "id",
            name=op.f("uq_automation_task_scope_history_organization_id_id"),
        ),
    )
    op.create_index(
        "ix_task_scope_history_at",
        "automation_task_scope_history",
        ["organization_id", "task_id", "recorded_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###

    op.execute("""
        INSERT INTO automation_task_scope_history
        (id,organization_id,task_id,assignee_membership_id,status,reporter_active,recorded_at)
        SELECT gen_random_uuid(),t.organization_id,t.id,t.assignee_membership_id,t.status,
               coalesce(m.is_active AND u.is_active,false),statement_timestamp()
        FROM tasks t LEFT JOIN memberships m
          ON m.organization_id=t.organization_id AND m.id=t.assignee_membership_id
        LEFT JOIN users u ON u.id=m.user_id
    """)
    op.execute("ALTER TABLE automation_task_scope_history ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE automation_task_scope_history FORCE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY scope_history_read ON automation_task_scope_history FOR SELECT TO app_runtime
        USING(organization_id=nullif(current_setting('app.organization_id',true),'')::uuid
          AND EXISTS(SELECT 1 FROM memberships m JOIN users u ON u.id=m.user_id
            WHERE m.organization_id=automation_task_scope_history.organization_id
              AND m.id=nullif(current_setting('app.membership_id',true),'')::uuid
              AND m.role IN ('MANAGER','ADMIN') AND m.is_active AND u.is_active))
    """)
    op.execute("GRANT SELECT ON automation_task_scope_history TO app_runtime")
    op.execute("""CREATE TRIGGER scope_history_immutable BEFORE UPDATE OR DELETE ON
        automation_task_scope_history FOR EACH ROW EXECUTE FUNCTION guard_daily_reporting_fact()""")
    op.execute("""
        CREATE FUNCTION record_reporting_task_scope() RETURNS trigger
        LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$
        BEGIN
          INSERT INTO public.automation_task_scope_history
          (id,organization_id,task_id,assignee_membership_id,status,reporter_active,recorded_at)
          SELECT gen_random_uuid(),t.organization_id,t.id,t.assignee_membership_id,t.status,
                 coalesce(m.is_active AND u.is_active,false),statement_timestamp()
          FROM public.tasks t LEFT JOIN public.memberships m
            ON m.organization_id=t.organization_id AND m.id=t.assignee_membership_id
          LEFT JOIN public.users u ON u.id=m.user_id
          WHERE (TG_TABLE_NAME='tasks' AND t.id=NEW.id)
             OR (TG_TABLE_NAME='memberships' AND t.assignee_membership_id=NEW.id)
             OR (TG_TABLE_NAME='users' AND m.user_id=NEW.id);
          RETURN NEW;
        END $$
    """)
    op.execute(
        "CREATE TRIGGER reporting_task_scope AFTER INSERT OR UPDATE OF "
        "assignee_membership_id,status ON tasks FOR EACH ROW "
        "EXECUTE FUNCTION record_reporting_task_scope()"
    )
    op.execute(
        "CREATE TRIGGER reporting_membership_scope AFTER UPDATE OF is_active ON memberships "
        "FOR EACH ROW EXECUTE FUNCTION record_reporting_task_scope()"
    )
    op.execute(
        "CREATE TRIGGER reporting_user_scope AFTER UPDATE OF is_active ON users "
        "FOR EACH ROW EXECUTE FUNCTION record_reporting_task_scope()"
    )


def downgrade() -> None:
    """Reverse the schema change when the revision supports it."""
    op.execute("DROP TRIGGER reporting_task_scope ON tasks")
    op.execute("DROP TRIGGER reporting_membership_scope ON memberships")
    op.execute("DROP TRIGGER reporting_user_scope ON users")
    op.execute("DROP FUNCTION record_reporting_task_scope()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_scope_history_at", table_name="automation_task_scope_history")
    op.drop_table("automation_task_scope_history")
    # ### end Alembic commands ###
