"""daily_summary_delivery

Revision ID: 0031
Revises: 0030
Create Date: 2026-10-04 16:56:03.926613
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0031"
down_revision: str | Sequence[str] | None = "0030"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_summary_triggers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("schedule_id", sa.Uuid(), nullable=False),
        sa.Column("window_id", sa.Uuid(), nullable=False),
        sa.Column("applied_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "schedule_id"],
            ["automation_schedules.organization_id", "automation_schedules.id"],
            name=op.f("fk_daily_summary_triggers_organization_id_schedule_id_automation_schedules"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "window_id"],
            ["reporting_windows.organization_id", "reporting_windows.id"],
            name=op.f("fk_daily_summary_triggers_organization_id_window_id_reporting_windows"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_summary_triggers")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_daily_summary_triggers_organization_id_id")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "schedule_id",
            "window_id",
            name=op.f("uq_daily_summary_triggers_organization_id_schedule_id_window_id"),
        ),
    )
    op.create_index(
        "ix_summary_trigger_window",
        "daily_summary_triggers",
        ["organization_id", "window_id"],
        unique=False,
    )
    op.create_table(
        "daily_summary_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("trigger_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "project_id"],
            ["projects.organization_id", "projects.id"],
            name=op.f("fk_daily_summary_snapshots_organization_id_project_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "trigger_id"],
            ["daily_summary_triggers.organization_id", "daily_summary_triggers.id"],
            name=op.f(
                "fk_daily_summary_snapshots_organization_id_trigger_id_daily_summary_triggers"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_summary_snapshots")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_daily_summary_snapshots_organization_id_id")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "trigger_id",
            name=op.f("uq_daily_summary_snapshots_organization_id_trigger_id"),
        ),
    )
    op.create_index(
        "ix_summary_snapshot_project",
        "daily_summary_snapshots",
        ["organization_id", "project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "daily_summary_deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=160), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "state IN ('PENDING','RUNNING','DELIVERED','FAILED','CANCELLED')",
            name=op.f("ck_daily_summary_deliveries_state"),
        ),
        sa.CheckConstraint(
            "attempts BETWEEN 0 AND 3", name=op.f("ck_daily_summary_deliveries_attempts")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "recipient_id"],
            ["memberships.organization_id", "memberships.id"],
            name=op.f("fk_daily_summary_deliveries_organization_id_recipient_id_memberships"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "snapshot_id"],
            ["daily_summary_snapshots.organization_id", "daily_summary_snapshots.id"],
            name=op.f(
                "fk_daily_summary_deliveries_organization_id_snapshot_id_daily_summary_snapshots"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_summary_deliveries")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_daily_summary_deliveries_organization_id_id")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "snapshot_id",
            "recipient_id",
            name=op.f("uq_daily_summary_deliveries_organization_id_snapshot_id_recipient_id"),
        ),
    )
    op.create_index(
        "ix_summary_delivery_claim",
        "daily_summary_deliveries",
        ["organization_id", "state", "retry_at", "lease_until"],
        unique=False,
    )
    op.create_index(
        "ix_summary_delivery_feed",
        "daily_summary_deliveries",
        ["organization_id", "recipient_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###

    tenant = "organization_id=nullif(current_setting('app.organization_id',true),'')::uuid"
    active = """EXISTS(SELECT 1 FROM memberships m JOIN users u ON u.id=m.user_id
        WHERE m.organization_id={table}.organization_id
          AND m.id=nullif(current_setting('app.membership_id',true),'')::uuid
          AND m.is_active AND u.is_active {role})"""
    for table in ("daily_summary_triggers", "daily_summary_snapshots", "daily_summary_deliveries"):
        manager = active.format(table=table, role="AND m.role IN ('MANAGER','ADMIN')")
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(f"GRANT SELECT,INSERT ON {table} TO app_runtime")
        read = f"({manager})"
        if table == "daily_summary_deliveries":
            op.execute(f"GRANT UPDATE ON {table} TO app_runtime")
            owner = active.format(
                table=table, role="AND m.id=daily_summary_deliveries.recipient_id"
            )
            read = f"(({manager}) OR ({owner}))"
            op.execute(
                f"CREATE POLICY summary_update ON {table} FOR UPDATE TO app_runtime "
                f"USING({tenant} AND ({manager})) WITH CHECK({tenant} AND ({manager}))"
            )
        else:
            op.execute(
                f"CREATE TRIGGER summary_immutable BEFORE UPDATE OR DELETE ON {table} "
                "FOR EACH ROW EXECUTE FUNCTION guard_daily_reporting_fact()"
            )
        op.execute(
            f"CREATE POLICY summary_read ON {table} FOR SELECT TO app_runtime "
            f"USING({tenant} AND {read})"
        )
        op.execute(
            f"CREATE POLICY summary_insert ON {table} FOR INSERT TO app_runtime "
            f"WITH CHECK({tenant} AND ({manager}))"
        )
    op.execute("""CREATE FUNCTION guard_delivered_summary() RETURNS trigger
        LANGUAGE plpgsql AS $$ BEGIN
          IF OLD.state='DELIVERED' THEN RAISE EXCEPTION 'Delivered summary is immutable'; END IF;
          RETURN NEW;
        END $$""")
    op.execute("""CREATE TRIGGER delivered_summary_immutable BEFORE UPDATE OR DELETE
        ON daily_summary_deliveries FOR EACH ROW EXECUTE FUNCTION guard_delivered_summary()""")


def downgrade() -> None:
    """Reverse the schema change when the revision supports it."""
    op.execute("DROP TRIGGER delivered_summary_immutable ON daily_summary_deliveries")
    op.execute("DROP FUNCTION guard_delivered_summary()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_summary_delivery_feed", table_name="daily_summary_deliveries")
    op.drop_index("ix_summary_delivery_claim", table_name="daily_summary_deliveries")
    op.drop_table("daily_summary_deliveries")
    op.drop_index("ix_summary_snapshot_project", table_name="daily_summary_snapshots")
    op.drop_table("daily_summary_snapshots")
    op.drop_index("ix_summary_trigger_window", table_name="daily_summary_triggers")
    op.drop_table("daily_summary_triggers")
    # ### end Alembic commands ###
