"""report snapshots

Revision ID: 0032
Revises: 0031
Create Date: 2026-10-04 23:16:42.155987
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0032"
down_revision: str | Sequence[str] | None = "0031"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("locale", sa.String(length=2), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("selected_version_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_membership_id", sa.Uuid(), nullable=False),
        sa.Column("narrative_requested", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('DAILY','WEEKLY')", name=op.f("ck_reports_kind")),
        sa.CheckConstraint("locale IN ('vi','en')", name=op.f("ck_reports_locale")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_reports_version")),
        sa.ForeignKeyConstraint(
            ["organization_id", "created_by_membership_id"],
            ["memberships.organization_id", "memberships.id"],
            name=op.f("fk_reports_organization_id_created_by_membership_id_memberships"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "project_id"],
            ["projects.organization_id", "projects.id"],
            name=op.f("fk_reports_organization_id_project_id_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint("organization_id", "id", name=op.f("uq_reports_organization_id_id")),
    )
    op.create_index(
        "ix_reports_project_timeline",
        "reports",
        ["organization_id", "project_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "report_metric_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(snapshot_hash)=64", name=op.f("ck_report_metric_snapshots_hash")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "project_id"],
            ["projects.organization_id", "projects.id"],
            name=op.f("fk_report_metric_snapshots_organization_id_project_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "report_id"],
            ["reports.organization_id", "reports.id"],
            name=op.f("fk_report_metric_snapshots_organization_id_report_id_reports"),
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_metric_snapshots")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_report_metric_snapshots_organization_id_id")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "report_id",
            "id",
            name=op.f("uq_report_metric_snapshots_organization_id_report_id_id"),
        ),
    )
    op.create_index(
        "ix_report_snapshots_project",
        "report_metric_snapshots",
        ["organization_id", "project_id", "captured_at", "id"],
        unique=False,
    )
    op.create_table(
        "report_snapshot_receipts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "snapshot_id"],
            ["report_metric_snapshots.organization_id", "report_metric_snapshots.id"],
            name=op.f(
                "fk_report_snapshot_receipts_organization_id_snapshot_id_report_metric_snapshots"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_snapshot_receipts")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_report_snapshot_receipts_organization_id_id")
        ),
    )
    op.create_index(
        "ix_report_receipts_snapshot",
        "report_snapshot_receipts",
        ["organization_id", "snapshot_id", "id"],
        unique=False,
    )
    op.create_table(
        "report_snapshot_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "snapshot_id"],
            ["report_metric_snapshots.organization_id", "report_metric_snapshots.id"],
            name=op.f(
                "fk_report_snapshot_sources_organization_id_snapshot_id_report_metric_snapshots"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "task_id"],
            ["tasks.organization_id", "tasks.id"],
            name=op.f("fk_report_snapshot_sources_organization_id_task_id_tasks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_snapshot_sources")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_report_snapshot_sources_organization_id_id")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "snapshot_id",
            "task_id",
            name=op.f("uq_report_snapshot_sources_organization_id_snapshot_id_task_id"),
        ),
    )
    op.create_index(
        "ix_report_sources_snapshot",
        "report_snapshot_sources",
        ["organization_id", "snapshot_id", "id"],
        unique=False,
    )
    op.create_table(
        "report_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("origin", sa.String(length=24), nullable=False),
        sa.Column("locale", sa.String(length=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("locale IN ('vi','en')", name=op.f("ck_report_versions_locale")),
        sa.CheckConstraint("origin IN ('METRICS_ONLY')", name=op.f("ck_report_versions_origin")),
        sa.ForeignKeyConstraint(
            ["organization_id", "report_id", "snapshot_id"],
            [
                "report_metric_snapshots.organization_id",
                "report_metric_snapshots.report_id",
                "report_metric_snapshots.id",
            ],
            name=op.f(
                "fk_report_versions_organization_id_report_id_snapshot_id_report_metric_snapshots"
            ),
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_versions")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_report_versions_organization_id_id")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "report_id",
            "id",
            name=op.f("uq_report_versions_organization_id_report_id_id"),
        ),
    )
    op.create_index(
        "ix_report_versions_timeline",
        "report_versions",
        ["organization_id", "report_id", "created_at", "id"],
        unique=False,
    )
    # Circular report ownership constraints must be added after both target tables exist.
    for name, target, pointer in (
        ("fk_reports_owned_snapshot", "report_metric_snapshots", "snapshot_id"),
        ("fk_reports_owned_version", "report_versions", "selected_version_id"),
    ):
        op.create_foreign_key(
            name,
            "reports",
            target,
            ["organization_id", "id", pointer],
            ["organization_id", "report_id", "id"],
            deferrable=True,
            initially="DEFERRED",
        )
    # ### end Alembic commands ###

    tenant = "organization_id=nullif(current_setting('app.organization_id',true),'')::uuid"
    for table in (
        "reports",
        "report_metric_snapshots",
        "report_versions",
        "report_snapshot_sources",
        "report_snapshot_receipts",
    ):
        manager = f"""EXISTS(SELECT 1 FROM memberships m JOIN users u ON u.id=m.user_id
            WHERE m.organization_id={table}.organization_id
            AND m.id=nullif(current_setting('app.membership_id',true),'')::uuid
            AND m.is_active AND u.is_active AND m.role IN ('MANAGER','ADMIN'))"""
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(f"GRANT SELECT,INSERT ON {table} TO app_runtime")
        op.execute(
            f"CREATE POLICY report_read ON {table} FOR SELECT TO app_runtime "
            f"USING({tenant} AND ({manager}))"
        )
        op.execute(
            f"CREATE POLICY report_insert ON {table} FOR INSERT TO app_runtime "
            f"WITH CHECK({tenant} AND ({manager}))"
        )
        if table == "reports":
            op.execute(f"GRANT UPDATE ON {table} TO app_runtime")
            op.execute(
                f"CREATE POLICY report_update ON {table} FOR UPDATE TO app_runtime "
                f"USING({tenant} AND ({manager})) WITH CHECK({tenant} AND ({manager}))"
            )
        else:
            op.execute(
                f"CREATE TRIGGER report_fact_immutable BEFORE UPDATE OR DELETE ON {table} "
                "FOR EACH ROW EXECUTE FUNCTION guard_daily_reporting_fact()"
            )


def downgrade() -> None:
    """Reverse the schema change when the revision supports it."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_reports_owned_version", "reports", type_="foreignkey")
    op.drop_constraint("fk_reports_owned_snapshot", "reports", type_="foreignkey")
    op.drop_index("ix_report_versions_timeline", table_name="report_versions")
    op.drop_table("report_versions")
    op.drop_index("ix_report_sources_snapshot", table_name="report_snapshot_sources")
    op.drop_table("report_snapshot_sources")
    op.drop_index("ix_report_receipts_snapshot", table_name="report_snapshot_receipts")
    op.drop_table("report_snapshot_receipts")
    op.drop_index("ix_report_snapshots_project", table_name="report_metric_snapshots")
    op.drop_table("report_metric_snapshots")
    op.drop_index("ix_reports_project_timeline", table_name="reports")
    op.drop_table("reports")
    # ### end Alembic commands ###
