"""report publications

Revision ID: 0033
Revises: 0032
Create Date: 2026-10-05 03:10:25.543796
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0033"
down_revision: str | Sequence[str] | None = "0032"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_review_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("report_version_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("actor_membership_id", sa.Uuid(), nullable=False),
        sa.Column("expected_report_version", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind='METRICS_ONLY_PUBLISHED'", name=op.f("ck_report_review_decisions_kind")
        ),
        sa.CheckConstraint(
            "expected_report_version>=1", name=op.f("ck_report_review_decisions_expected_version")
        ),
        sa.CheckConstraint(
            "length(snapshot_hash)=64", name=op.f("ck_report_review_decisions_hash")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "actor_membership_id"],
            ["memberships.organization_id", "memberships.id"],
            name=op.f("fk_report_review_decisions_organization_id_actor_membership_id_memberships"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "report_id", "report_version_id"],
            ["report_versions.organization_id", "report_versions.report_id", "report_versions.id"],
            name=op.f(
                "fk_report_review_decisions_organization_id_report_id_report_version_id_report_versions"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_review_decisions")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_report_review_decisions_organization_id_id")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "report_id",
            "report_version_id",
            "snapshot_hash",
            "actor_membership_id",
            "id",
            name=op.f(
                "uq_report_review_decisions_organization_id_report_id_report_version_id_snapshot_hash_actor_membership_id_id"
            ),
        ),
    )
    op.create_index(
        "ix_report_decisions_timeline",
        "report_review_decisions",
        ["organization_id", "report_id", "decided_at", "id"],
        unique=False,
    )
    op.create_table(
        "report_publications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("report_version_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("publisher_membership_id", sa.Uuid(), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(snapshot_hash)=64", name=op.f("ck_report_publications_hash")),
        sa.ForeignKeyConstraint(
            [
                "organization_id",
                "report_id",
                "report_version_id",
                "snapshot_hash",
                "publisher_membership_id",
                "decision_id",
            ],
            [
                "report_review_decisions.organization_id",
                "report_review_decisions.report_id",
                "report_review_decisions.report_version_id",
                "report_review_decisions.snapshot_hash",
                "report_review_decisions.actor_membership_id",
                "report_review_decisions.id",
            ],
            name=op.f(
                "fk_report_publications_organization_id_report_id_report_version_id_snapshot_hash_publisher_membership_id_decision_id_report_review_decisions"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_publications")),
        sa.UniqueConstraint(
            "organization_id",
            "decision_id",
            name=op.f("uq_report_publications_organization_id_decision_id"),
        ),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_report_publications_organization_id_id")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "report_id",
            "id",
            name=op.f("uq_report_publications_organization_id_report_id_id"),
        ),
    )
    op.create_index(
        "ix_report_publications_timeline",
        "report_publications",
        ["organization_id", "report_id", "published_at", "id"],
        unique=False,
    )
    op.add_column("reports", sa.Column("current_publication_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "fk_reports_owned_publication",
        "reports",
        "report_publications",
        ["organization_id", "id", "current_publication_id"],
        ["organization_id", "report_id", "id"],
        initially="DEFERRED",
        deferrable=True,
        use_alter=True,
    )
    # ### end Alembic commands ###
    tenant = "organization_id=nullif(current_setting('app.organization_id',true),'')::uuid"
    for table in ("report_review_decisions", "report_publications"):
        manager = f"""EXISTS(SELECT 1 FROM memberships m JOIN users u ON u.id=m.user_id
            WHERE m.organization_id={table}.organization_id
            AND m.id=nullif(current_setting('app.membership_id',true),'')::uuid
            AND m.is_active AND u.is_active AND m.role IN ('MANAGER','ADMIN'))"""
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(f"GRANT SELECT,INSERT ON {table} TO app_runtime")
        op.execute(
            f"CREATE POLICY report_read ON {table} FOR SELECT TO app_runtime "
            f"USING({tenant} AND ({manager}))"
        )
        op.execute(
            f"CREATE POLICY report_insert ON {table} FOR INSERT TO app_runtime "
            f"WITH CHECK({tenant} AND ({manager}))"
        )
        op.execute(
            f"CREATE TRIGGER report_fact_immutable BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION guard_daily_reporting_fact()"
        )


def downgrade() -> None:
    """Reverse the schema change when the revision supports it."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_reports_owned_publication", "reports", type_="foreignkey")
    op.drop_column("reports", "current_publication_id")
    op.drop_index("ix_report_publications_timeline", table_name="report_publications")
    op.drop_table("report_publications")
    op.drop_index("ix_report_decisions_timeline", table_name="report_review_decisions")
    op.drop_table("report_review_decisions")
    # ### end Alembic commands ###
