"""typed orchestration triggers

Revision ID: 0034
Revises: 0033
Create Date: 2026-10-05 04:37:21.060641
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0034"
down_revision: str | Sequence[str] | None = "0033"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_assistant_turns_organization_id_id_actor_membership_id"),
        "assistant_turns",
        ["organization_id", "id", "actor_membership_id"],
    )
    op.create_unique_constraint(
        op.f("uq_daily_summary_snapshots_organization_id_project_id_id"),
        "daily_summary_snapshots",
        ["organization_id", "project_id", "id"],
    )
    op.add_column(
        "orchestration_runs",
        sa.Column("trigger_kind", sa.String(length=24), server_default="CHAT_TURN", nullable=False),
    )
    op.add_column("orchestration_runs", sa.Column("actor_membership_id", sa.Uuid(), nullable=True))
    op.add_column("orchestration_runs", sa.Column("project_id", sa.Uuid(), nullable=True))
    op.add_column("orchestration_runs", sa.Column("report_id", sa.Uuid(), nullable=True))
    op.add_column("orchestration_runs", sa.Column("base_version_id", sa.Uuid(), nullable=True))
    op.add_column("orchestration_runs", sa.Column("snapshot_id", sa.Uuid(), nullable=True))
    op.add_column(
        "orchestration_runs", sa.Column("snapshot_hash", sa.String(length=64), nullable=True)
    )
    op.add_column("orchestration_runs", sa.Column("summary_id", sa.Uuid(), nullable=True))
    op.add_column(
        "orchestration_runs", sa.Column("request_key", sa.String(length=128), nullable=True)
    )
    op.alter_column("orchestration_runs", "turn_id", existing_type=sa.UUID(), nullable=True)
    op.create_index(
        "uq_orchestration_trigger_request",
        "orchestration_runs",
        ["organization_id", "actor_membership_id", "request_key"],
        unique=True,
        postgresql_where=sa.text("trigger_kind<>'CHAT_TURN'"),
    )
    op.create_unique_constraint(
        op.f("uq_report_metric_snapshots_organization_id_report_id_id_snapshot_hash"),
        "report_metric_snapshots",
        ["organization_id", "report_id", "id", "snapshot_hash"],
    )
    op.create_unique_constraint(
        op.f("uq_report_versions_organization_id_report_id_id_snapshot_id"),
        "report_versions",
        ["organization_id", "report_id", "id", "snapshot_id"],
    )
    op.create_unique_constraint(
        op.f("uq_reports_organization_id_project_id_id"),
        "reports",
        ["organization_id", "project_id", "id"],
    )
    op.execute(
        "UPDATE orchestration_runs r SET actor_membership_id=t.actor_membership_id "
        "FROM assistant_turns t WHERE r.organization_id=t.organization_id AND r.turn_id=t.id"
    )
    op.alter_column(
        "orchestration_runs", "actor_membership_id", existing_type=sa.Uuid(), nullable=False
    )
    op.create_check_constraint(
        "ck_orchestration_runs_trigger_shape",
        "orchestration_runs",
        "(trigger_kind='CHAT_TURN' AND turn_id IS NOT NULL AND project_id IS NULL "
        "AND report_id IS NULL AND base_version_id IS NULL AND snapshot_id IS NULL "
        "AND snapshot_hash IS NULL AND summary_id IS NULL AND request_key IS NULL) OR "
        "(trigger_kind IN ('REPORT_REQUEST','SUMMARY_JOB') AND turn_id IS NULL "
        "AND project_id IS NOT NULL AND report_id IS NOT NULL AND base_version_id IS NOT NULL "
        "AND snapshot_id IS NOT NULL AND snapshot_hash IS NOT NULL "
        "AND length(request_key) BETWEEN 16 AND 128 AND request_key IS NOT NULL "
        "AND ((trigger_kind='REPORT_REQUEST' AND summary_id IS NULL) OR "
        "(trigger_kind='SUMMARY_JOB' AND summary_id IS NOT NULL)))",
    )
    op.create_foreign_key(
        op.f("fk_orchestration_runs_organization_id_project_id_report_id_reports"),
        "orchestration_runs",
        "reports",
        ["organization_id", "project_id", "report_id"],
        ["organization_id", "project_id", "id"],
    )
    op.create_foreign_key(
        op.f("fk_orchestration_runs_organization_id_project_id_summary_id_daily_summary_snapshots"),
        "orchestration_runs",
        "daily_summary_snapshots",
        ["organization_id", "project_id", "summary_id"],
        ["organization_id", "project_id", "id"],
    )
    op.create_foreign_key(
        op.f(
            "fk_orchestration_runs_organization_id_report_id_base_version_id_snapshot_id_report_versions"
        ),
        "orchestration_runs",
        "report_versions",
        ["organization_id", "report_id", "base_version_id", "snapshot_id"],
        ["organization_id", "report_id", "id", "snapshot_id"],
    )
    op.create_foreign_key(
        op.f("fk_orchestration_runs_organization_id_actor_membership_id_memberships"),
        "orchestration_runs",
        "memberships",
        ["organization_id", "actor_membership_id"],
        ["organization_id", "id"],
    )
    op.create_foreign_key(
        op.f(
            "fk_orchestration_runs_organization_id_report_id_snapshot_id_snapshot_hash_report_metric_snapshots"
        ),
        "orchestration_runs",
        "report_metric_snapshots",
        ["organization_id", "report_id", "snapshot_id", "snapshot_hash"],
        ["organization_id", "report_id", "id", "snapshot_hash"],
    )
    op.create_foreign_key(
        op.f("fk_orchestration_runs_organization_id_turn_id_actor_membership_id_assistant_turns"),
        "orchestration_runs",
        "assistant_turns",
        ["organization_id", "turn_id", "actor_membership_id"],
        ["organization_id", "id", "actor_membership_id"],
    )
    # ### end Alembic commands ###
    op.execute("DROP POLICY orchestration_runs_tenant_owner ON orchestration_runs")
    owner = """organization_id=nullif(current_setting('app.organization_id',true),'')::uuid AND (
        (trigger_kind='CHAT_TURN' AND EXISTS (SELECT 1 FROM assistant_turns t
         WHERE t.organization_id=orchestration_runs.organization_id
         AND t.id=orchestration_runs.turn_id)) OR
        (trigger_kind<>'CHAT_TURN'
         AND actor_membership_id=nullif(current_setting('app.membership_id',true),'')::uuid
         AND EXISTS (SELECT 1 FROM memberships m JOIN users u ON u.id=m.user_id
         WHERE m.organization_id=orchestration_runs.organization_id
         AND m.id=orchestration_runs.actor_membership_id AND m.is_active AND u.is_active
         AND m.role IN ('MANAGER','ADMIN'))))"""
    op.execute(
        f"CREATE POLICY orchestration_runs_tenant_owner ON orchestration_runs "
        f"USING ({owner}) WITH CHECK ({owner})"
    )


def downgrade() -> None:
    """Reverse the schema change when the revision supports it."""
    op.execute("""DO $$ BEGIN
        IF EXISTS (SELECT 1 FROM orchestration_runs WHERE trigger_kind<>'CHAT_TURN') THEN
            RAISE EXCEPTION 'non-chat runs require an explicit recovery/export before downgrade';
        END IF; END $$""")
    op.execute("DROP POLICY orchestration_runs_tenant_owner ON orchestration_runs")
    owner = """organization_id=nullif(current_setting('app.organization_id',true),'')::uuid
        AND EXISTS (SELECT 1 FROM assistant_turns t
        WHERE t.organization_id=orchestration_runs.organization_id
         AND t.id=orchestration_runs.turn_id)"""
    op.execute(
        f"CREATE POLICY orchestration_runs_tenant_owner ON orchestration_runs "
        f"USING ({owner}) WITH CHECK ({owner})"
    )
    op.drop_constraint("ck_orchestration_runs_trigger_shape", "orchestration_runs", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_orchestration_runs_organization_id_turn_id_actor_membership_id_assistant_turns"),
        "orchestration_runs",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f(
            "fk_orchestration_runs_organization_id_report_id_snapshot_id_snapshot_hash_report_metric_snapshots"
        ),
        "orchestration_runs",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_orchestration_runs_organization_id_actor_membership_id_memberships"),
        "orchestration_runs",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f(
            "fk_orchestration_runs_organization_id_report_id_base_version_id_snapshot_id_report_versions"
        ),
        "orchestration_runs",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_orchestration_runs_organization_id_project_id_summary_id_daily_summary_snapshots"),
        "orchestration_runs",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_orchestration_runs_organization_id_project_id_report_id_reports"),
        "orchestration_runs",
        type_="foreignkey",
    )
    op.drop_constraint(op.f("uq_reports_organization_id_project_id_id"), "reports", type_="unique")
    op.drop_constraint(
        op.f("uq_report_versions_organization_id_report_id_id_snapshot_id"),
        "report_versions",
        type_="unique",
    )
    op.drop_constraint(
        op.f("uq_report_metric_snapshots_organization_id_report_id_id_snapshot_hash"),
        "report_metric_snapshots",
        type_="unique",
    )
    op.drop_index(
        "uq_orchestration_trigger_request",
        table_name="orchestration_runs",
        postgresql_where=sa.text("trigger_kind<>'CHAT_TURN'"),
    )
    op.alter_column("orchestration_runs", "turn_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("orchestration_runs", "request_key")
    op.drop_column("orchestration_runs", "summary_id")
    op.drop_column("orchestration_runs", "snapshot_hash")
    op.drop_column("orchestration_runs", "snapshot_id")
    op.drop_column("orchestration_runs", "base_version_id")
    op.drop_column("orchestration_runs", "report_id")
    op.drop_column("orchestration_runs", "project_id")
    op.drop_column("orchestration_runs", "actor_membership_id")
    op.drop_column("orchestration_runs", "trigger_kind")
    op.drop_constraint(
        op.f("uq_daily_summary_snapshots_organization_id_project_id_id"),
        "daily_summary_snapshots",
        type_="unique",
    )
    op.drop_constraint(
        op.f("uq_assistant_turns_organization_id_id_actor_membership_id"),
        "assistant_turns",
        type_="unique",
    )
    # ### end Alembic commands ###
