"""report_generation_jobs

Revision ID: 0035
Revises: 0034
Create Date: 2026-10-05 05:47:31.095140
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0035"
down_revision: str | Sequence[str] | None = "0034"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_generation_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("base_version_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("requester_membership_id", sa.Uuid(), nullable=False),
        sa.Column("request_key", sa.String(length=128), nullable=False),
        sa.Column("expected_report_version", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("claims", sa.Integer(), server_default="0", nullable=False),
        sa.Column("fence", sa.Integer(), server_default="0", nullable=False),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("orchestration_run_id", sa.Uuid(), nullable=True),
        sa.Column("proposed_version_id", sa.Uuid(), nullable=True),
        sa.Column("safe_error_code", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(state='RUNNING') = (lease_owner IS NOT NULL AND lease_until IS NOT NULL)",
            name=op.f("ck_report_generation_jobs_lease"),
        ),
        sa.CheckConstraint(
            "state IN ('QUEUED','RUNNING','AWAITING_REVIEW','AI_UNAVAILABLE','FAILED')",
            name=op.f("ck_report_generation_jobs_state"),
        ),
        sa.CheckConstraint(
            "(started_at IS NULL) = (deadline IS NULL)",
            name=op.f("ck_report_generation_jobs_deadline"),
        ),
        sa.CheckConstraint(
            "claims BETWEEN 0 AND 3 AND fence>=0 AND expected_report_version>=1",
            name=op.f("ck_report_generation_jobs_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "orchestration_run_id"],
            ["orchestration_runs.organization_id", "orchestration_runs.id"],
            name=op.f(
                "fk_report_generation_jobs_organization_id_orchestration_run_id_orchestration_runs"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "report_id", "base_version_id", "snapshot_id"],
            [
                "report_versions.organization_id",
                "report_versions.report_id",
                "report_versions.id",
                "report_versions.snapshot_id",
            ],
            name=op.f(
                "fk_report_generation_jobs_organization_id_report_id_base_version_id_snapshot_id_report_versions"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "report_id", "proposed_version_id"],
            ["report_versions.organization_id", "report_versions.report_id", "report_versions.id"],
            name=op.f(
                "fk_report_generation_jobs_organization_id_report_id_proposed_version_id_report_versions"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "report_id", "snapshot_id", "snapshot_hash"],
            [
                "report_metric_snapshots.organization_id",
                "report_metric_snapshots.report_id",
                "report_metric_snapshots.id",
                "report_metric_snapshots.snapshot_hash",
            ],
            name=op.f(
                "fk_report_generation_jobs_organization_id_report_id_snapshot_id_snapshot_hash_report_metric_snapshots"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "requester_membership_id"],
            ["memberships.organization_id", "memberships.id"],
            name=op.f(
                "fk_report_generation_jobs_organization_id_requester_membership_id_memberships"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_generation_jobs")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_report_generation_jobs_organization_id_id")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "requester_membership_id",
            "request_key",
            name=op.f(
                "uq_report_generation_jobs_organization_id_requester_membership_id_request_key"
            ),
        ),
    )
    op.create_index(
        "ix_report_generation_claim",
        "report_generation_jobs",
        ["organization_id", "state", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_report_generation_report",
        "report_generation_jobs",
        ["organization_id", "report_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "report_generation_usage",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("generation_id", sa.Uuid(), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("input_reserved", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_reserved", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tools", sa.Integer(), server_default="0", nullable=False),
        sa.Column("retries", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "reservations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempts BETWEEN 0 AND 3 AND input_reserved BETWEEN 0 AND 48000 AND "
            "output_reserved BETWEEN 0 AND 8000",
            name=op.f("ck_report_generation_usage_model_bounds"),
        ),
        sa.CheckConstraint(
            "tools BETWEEN 0 AND 6 AND retries BETWEEN 0 AND 1",
            name=op.f("ck_report_generation_usage_tool_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "generation_id"],
            ["report_generation_jobs.organization_id", "report_generation_jobs.id"],
            name=op.f(
                "fk_report_generation_usage_organization_id_generation_id_report_generation_jobs"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "organization_id", "generation_id", name=op.f("pk_report_generation_usage")
        ),
    )
    op.add_column(
        "report_versions",
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
    )
    op.drop_constraint(op.f("ck_report_versions_origin"), "report_versions", type_="check")
    op.create_check_constraint(
        op.f("ck_report_versions_origin"),
        "report_versions",
        "origin IN ('METRICS_ONLY','AI_PROPOSED')",
    )
    tenant = "organization_id=nullif(current_setting('app.organization_id',true),'')::uuid"
    for table in ("report_generation_jobs", "report_generation_usage"):
        manager = f"""(nullif(current_setting('app.membership_id',true),'') IS NULL OR EXISTS(
            SELECT 1 FROM memberships m JOIN users u ON u.id=m.user_id
            WHERE m.organization_id={table}.organization_id
            AND m.id=nullif(current_setting('app.membership_id',true),'')::uuid
            AND m.is_active AND u.is_active AND m.role IN ('MANAGER','ADMIN')))"""
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(f"GRANT SELECT,INSERT,UPDATE ON {table} TO app_runtime")
        op.execute(
            f"CREATE POLICY report_generation_scope ON {table} TO app_runtime "
            f"USING ({tenant} AND {manager}) WITH CHECK ({tenant} AND {manager})"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Refuse to silently discard business narrative versions.
    op.execute(
        "DO $$ BEGIN IF EXISTS(SELECT 1 FROM report_versions WHERE origin='AI_PROPOSED') "
        "THEN RAISE EXCEPTION 'Narrative versions require explicit recovery before downgrade'; "
        "END IF; END $$"
    )
    op.drop_constraint(op.f("ck_report_versions_origin"), "report_versions", type_="check")
    op.create_check_constraint(
        op.f("ck_report_versions_origin"), "report_versions", "origin IN ('METRICS_ONLY')"
    )
    """Reverse the schema change when the revision supports it."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("report_versions", "payload")
    op.drop_table("report_generation_usage")
    op.drop_index("ix_report_generation_report", table_name="report_generation_jobs")
    op.drop_index("ix_report_generation_claim", table_name="report_generation_jobs")
    op.drop_table("report_generation_jobs")
    # ### end Alembic commands ###
