"""report_feedback

Revision ID: 0036
Revises: 0035
Create Date: 2026-10-06 10:16:23.196004
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0036"
down_revision: str | Sequence[str] | None = "0035"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("report_version_id", sa.Uuid(), nullable=False),
        sa.Column("original_version_id", sa.Uuid(), nullable=False),
        sa.Column("generation_id", sa.Uuid(), nullable=False),
        sa.Column("actor_membership_id", sa.Uuid(), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=True),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=2000), nullable=True),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "decision IN ('ACCEPT','EDIT','REJECT')", name=op.f("ck_feedback_decision")
        ),
        sa.CheckConstraint(
            "kind IN ('TERMINAL_QUALITY','ADVISORY') AND "
            "((kind='TERMINAL_QUALITY') = (decision_id IS NOT NULL))",
            name=op.f("ck_feedback_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "actor_membership_id"],
            ["memberships.organization_id", "memberships.id"],
            name=op.f("fk_feedback_organization_id_actor_membership_id_memberships"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "generation_id"],
            ["report_generation_jobs.organization_id", "report_generation_jobs.id"],
            name=op.f("fk_feedback_organization_id_generation_id_report_generation_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "report_id", "original_version_id"],
            ["report_versions.organization_id", "report_versions.report_id", "report_versions.id"],
            name=op.f("fk_feedback_organization_id_report_id_original_version_id_report_versions"),
        ),
        sa.ForeignKeyConstraint(
            [
                "organization_id",
                "report_id",
                "report_version_id",
                "snapshot_hash",
                "actor_membership_id",
                "decision_id",
            ],
            [
                "report_review_decisions.organization_id",
                "report_review_decisions.report_id",
                "report_review_decisions.report_version_id",
                "report_review_decisions.snapshot_hash",
                "report_review_decisions.actor_membership_id",
                "report_review_decisions.id",
            ],
            name=op.f(
                "fk_feedback_organization_id_report_id_report_version_id_snapshot_hash_actor_membership_id_decision_id_report_review_decisions"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "report_id", "report_version_id"],
            ["report_versions.organization_id", "report_versions.report_id", "report_versions.id"],
            name=op.f("fk_feedback_organization_id_report_id_report_version_id_report_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
        sa.UniqueConstraint("organization_id", "id", name=op.f("uq_feedback_organization_id_id")),
    )
    op.create_index(
        "ix_feedback_report",
        "feedback",
        ["organization_id", "report_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "uq_feedback_terminal_generation",
        "feedback",
        ["organization_id", "generation_id"],
        unique=True,
        postgresql_where=sa.text("kind='TERMINAL_QUALITY'"),
    )
    op.create_table(
        "report_version_verifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("report_version_id", sa.Uuid(), nullable=False),
        sa.Column("verification_job_id", sa.Uuid(), nullable=False),
        sa.Column("verdict", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "report_id", "report_version_id"],
            ["report_versions.organization_id", "report_versions.report_id", "report_versions.id"],
            name=op.f(
                "fk_report_version_verifications_organization_id_report_id_report_version_id_report_versions"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "verification_job_id"],
            ["report_generation_jobs.organization_id", "report_generation_jobs.id"],
            name=op.f(
                "fk_report_version_verifications_organization_id_verification_job_id_report_generation_jobs"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_version_verifications")),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_report_version_verifications_organization_id_id")
        ),
        sa.UniqueConstraint(
            "organization_id",
            "verification_job_id",
            name=op.f("uq_report_version_verifications_organization_id_verification_job_id"),
        ),
    )
    op.create_index(
        "ix_report_verifications_version",
        "report_version_verifications",
        ["organization_id", "report_id", "report_version_id", "created_at"],
        unique=False,
    )
    op.add_column(
        "report_generation_jobs",
        sa.Column("job_type", sa.String(length=24), server_default="DRAFT", nullable=False),
    )
    op.add_column(
        "report_generation_jobs", sa.Column("original_generation_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        op.f(
            "fk_report_generation_jobs_organization_id_original_generation_id_report_generation_jobs"
        ),
        "report_generation_jobs",
        "report_generation_jobs",
        ["organization_id", "original_generation_id"],
        ["organization_id", "id"],
    )
    op.drop_constraint(op.f("ck_report_versions_origin"), "report_versions", type_="check")
    op.create_check_constraint(
        op.f("ck_report_versions_origin"),
        "report_versions",
        "origin IN ('METRICS_ONLY','AI_PROPOSED','AI_EDITED')",
    )
    op.drop_constraint(
        op.f("ck_report_review_decisions_kind"), "report_review_decisions", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_report_review_decisions_kind"),
        "report_review_decisions",
        "kind IN ('METRICS_ONLY_PUBLISHED','ACCEPT','REJECT')",
    )
    op.create_check_constraint(
        op.f("ck_report_generation_jobs_job_type"),
        "report_generation_jobs",
        "job_type IN ('DRAFT','EDIT_VERIFICATION') AND "
        "((job_type='EDIT_VERIFICATION') = (original_generation_id IS NOT NULL))",
    )
    tenant = "organization_id=nullif(current_setting('app.organization_id',true),'')::uuid"
    for table in ("feedback", "report_version_verifications"):
        manager = f"""EXISTS(SELECT 1 FROM memberships m JOIN users u ON u.id=m.user_id
            WHERE m.organization_id={table}.organization_id
            AND m.id=nullif(current_setting('app.membership_id',true),'')::uuid
            AND m.is_active AND u.is_active AND m.role IN ('MANAGER','ADMIN'))"""
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(f"GRANT SELECT,INSERT ON {table} TO app_runtime")
        op.execute(
            f"CREATE POLICY feedback_scope ON {table} TO app_runtime "
            f"USING ({tenant} AND {manager}) WITH CHECK ({tenant} AND {manager})"
        )
        op.execute(
            f"CREATE TRIGGER report_fact_immutable BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION guard_daily_reporting_fact()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when the revision supports it."""
    op.execute(
        "DO $$ BEGIN IF EXISTS(SELECT 1 FROM feedback) OR "
        "EXISTS(SELECT 1 FROM report_version_verifications) OR "
        "EXISTS(SELECT 1 FROM report_versions WHERE origin='AI_EDITED') OR "
        "EXISTS(SELECT 1 FROM report_generation_jobs WHERE job_type='EDIT_VERIFICATION') "
        "THEN RAISE EXCEPTION 'Review records require explicit recovery before downgrade'; "
        "END IF; END $$"
    )
    op.drop_constraint(
        op.f("ck_report_generation_jobs_job_type"), "report_generation_jobs", type_="check"
    )
    op.drop_constraint(op.f("ck_report_versions_origin"), "report_versions", type_="check")
    op.create_check_constraint(
        op.f("ck_report_versions_origin"),
        "report_versions",
        "origin IN ('METRICS_ONLY','AI_PROPOSED')",
    )
    op.drop_constraint(
        op.f("ck_report_review_decisions_kind"), "report_review_decisions", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_report_review_decisions_kind"),
        "report_review_decisions",
        "kind='METRICS_ONLY_PUBLISHED'",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f(
            "fk_report_generation_jobs_organization_id_original_generation_id_report_generation_jobs"
        ),
        "report_generation_jobs",
        type_="foreignkey",
    )
    op.drop_column("report_generation_jobs", "original_generation_id")
    op.drop_column("report_generation_jobs", "job_type")
    op.drop_index("ix_report_verifications_version", table_name="report_version_verifications")
    op.drop_table("report_version_verifications")
    op.drop_index(
        "uq_feedback_terminal_generation",
        table_name="feedback",
        postgresql_where=sa.text("kind='TERMINAL_QUALITY'"),
    )
    op.drop_index("ix_feedback_report", table_name="feedback")
    op.drop_table("feedback")
    # ### end Alembic commands ###
