"""feedback_outcomes

Revision ID: 0038
Revises: 0037
Create Date: 2026-10-07 08:53:39.303777
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0038"
down_revision: str | Sequence[str] | None = "0037"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback_outcomes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("feedback_id", sa.Uuid(), nullable=False),
        sa.Column("actor_membership_id", sa.Uuid(), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("source_version", sa.Integer(), nullable=False),
        sa.Column("task_transition_id", sa.Uuid(), nullable=True),
        sa.Column("actual_task_id", sa.Uuid(), nullable=True),
        sa.Column("observation_id", sa.Uuid(), nullable=True),
        sa.Column("blocker_transition_id", sa.Uuid(), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(source_type='TASK_TRANSITION' AND task_transition_id IS NOT NULL AND sourc"
            "e_id=task_transition_id AND actual_task_id IS NULL AND blocker_transition_i"
            "d IS NULL AND observation_id IS NULL) OR (source_type='TASK_ACTUALS' AND ac"
            "tual_task_id IS NOT NULL AND source_id=actual_task_id AND task_transition_i"
            "d IS NULL AND blocker_transition_id IS NULL) OR (source_type='BLOCKER_RESOL"
            "UTION' AND blocker_transition_id IS NOT NULL AND source_id=blocker_transiti"
            "on_id AND actual_task_id IS NULL AND task_transition_id IS NULL AND observa"
            "tion_id IS NULL)",
            name=op.f("ck_feedback_outcomes_source"),
        ),
        sa.CheckConstraint(
            "state IN ('AVAILABLE','UNKNOWN') AND schema_version='feedback-outcome.v1' A"
            "ND source_version>=0",
            name=op.f("ck_feedback_outcomes_state"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "actor_membership_id"],
            ["memberships.organization_id", "memberships.id"],
            name=op.f("fk_feedback_outcomes_organization_id_actor_membership_id_memberships"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "actual_task_id"],
            ["tasks.organization_id", "tasks.id"],
            name=op.f("fk_feedback_outcomes_organization_id_actual_task_id_tasks"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "blocker_transition_id"],
            ["blocker_transitions.organization_id", "blocker_transitions.id"],
            name=op.f(
                "fk_feedback_outcomes_organization_id_blocker_transition_id_blocker_transitions"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "feedback_id"],
            ["feedback.organization_id", "feedback.id"],
            name=op.f("fk_feedback_outcomes_organization_id_feedback_id_feedback"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "observation_id"],
            ["task_progress_observations.organization_id", "task_progress_observations.id"],
            name=op.f(
                "fk_feedback_outcomes_organization_id_observation_id_task_progress_observations"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "task_transition_id"],
            ["task_status_transitions.organization_id", "task_status_transitions.id"],
            name=op.f(
                "fk_feedback_outcomes_organization_id_task_transition_id_task_status_transitions"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback_outcomes")),
        sa.UniqueConstraint(
            "organization_id",
            "feedback_id",
            "source_type",
            "source_id",
            "source_version",
            name="uq_feedback_outcome_source",
        ),
        sa.UniqueConstraint(
            "organization_id", "id", name=op.f("uq_feedback_outcomes_organization_id_id")
        ),
    )
    op.create_index(
        "ix_feedback_outcomes_feedback",
        "feedback_outcomes",
        ["organization_id", "feedback_id", "recorded_at", "id"],
        unique=False,
    )
    tenant = "organization_id=nullif(current_setting('app.organization_id',true),'')::uuid"
    manager = """EXISTS(SELECT 1 FROM memberships m JOIN users u ON u.id=m.user_id
        WHERE m.organization_id=feedback_outcomes.organization_id
        AND m.id=nullif(current_setting('app.membership_id',true),'')::uuid
        AND m.is_active AND u.is_active AND m.role IN ('MANAGER','ADMIN'))"""
    op.execute("ALTER TABLE feedback_outcomes ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE feedback_outcomes FORCE ROW LEVEL SECURITY")
    op.execute("GRANT SELECT,INSERT ON feedback_outcomes TO app_runtime")
    op.execute(
        f"CREATE POLICY feedback_outcome_scope ON feedback_outcomes TO app_runtime "
        f"USING ({tenant} AND {manager}) WITH CHECK ({tenant} AND {manager})"
    )
    op.execute(
        "CREATE TRIGGER feedback_outcome_immutable BEFORE UPDATE OR DELETE ON feedba"
        "ck_outcomes FOR EACH ROW EXECUTE FUNCTION guard_daily_reporting_fact()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change when the revision supports it."""
    op.execute(
        "DO $$ BEGIN IF EXISTS(SELECT 1 FROM feedback_outcomes) THEN RAISE EXCEPTION"
        " 'Outcome history requires explicit recovery before downgrade'; END IF; END"
        " $$"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_feedback_outcomes_feedback", table_name="feedback_outcomes")
    op.drop_table("feedback_outcomes")
    # ### end Alembic commands ###
