import { execFileSync } from "node:child_process";
import { resolve } from "node:path";
import { expect, test } from "@playwright/test";

test("Manager asks about saved risk and receives a grounded card without changing the score", async ({ page }) => {
 await page.goto("/login");
 await page.getByLabel("Email").fill("manager@example.test");
 await page.getByLabel("Mật khẩu").fill("WorkDemo123!");
 await page.getByRole("button", { name: "Đăng nhập" }).click();
 await expect(page.getByRole("button", { name: "Đăng xuất" })).toBeVisible();
 const headers = { "Idempotency-Key": crypto.randomUUID() };
 const projectResponse = await page.request.post("/api/v1/projects", { headers, data: {name:`Risk chat ${Date.now()}`,description:"Delivery review"} });
 expect(projectResponse.status()).toBe(201);
 const project = await projectResponse.json();
 const weekResponse = await page.request.post(`/api/v1/projects/${project.id}/weeks`, {headers: {"Idempotency-Key":crypto.randomUUID()},data:{week_number:1,start_date:"2026-09-28",end_date:"2026-10-04",objective:"Review delivery"}});
 expect(weekResponse.status()).toBe(201);
 const week=await weekResponse.json();
 const taskResponse = await page.request.post("/api/v1/tasks", { headers: {"Idempotency-Key":crypto.randomUUID()},data:{project_id:project.id,project_week_id:week.id,estimated_effort_hours:8,title:`Khảo sát địa điểm ${Date.now()}`,description:"Delivery review"} });
 expect(taskResponse.status(), await taskResponse.text()).toBe(201);
 const task = await taskResponse.json();
 execFileSync("uv", ["run", "--directory", resolve(process.cwd(), "../backend"), "python", resolve(process.cwd(), "e2e/fixtures/risk-seed.py"), task.id], { env: { ...process.env, PYTHONPATH: resolve(process.cwd(), "../backend"), APP_DATABASE_URL: "postgresql+psycopg://work_management:work_management@localhost:5432/work_management_e2e" } });
 const before = await (await page.request.get(`/api/v1/risks?task_id=${task.id}`)).json();
 await page.getByRole("navigation", { name: "Điều hướng chính" }).getByRole("button", { name: "Cuộc trò chuyện mới" }).click();
 await page.getByLabel("Nhắn cho Trợ lý AI").fill(`Giải thích rủi ro công việc ${task.id}`);
 await page.getByRole("button", { name: "Gửi" }).click();
 const card=page.getByRole("region", {name:"Đánh giá rủi ro",exact:true});
 await expect(card).toBeVisible();
 await expect(card.getByText("83", {exact:true})).toBeVisible();
 await expect(card.getByText("Cần kiểm tra hạn hoàn thành và blocker.", {exact:true})).toBeVisible();
 await expect(card.getByText("Trao đổi lại lịch giao với người phụ trách.", {exact:true})).toBeVisible();
 await expect(card.getByRole("button", {name:/phê duyệt/i})).toHaveCount(0);
 await card.screenshot({path:"/tmp/task11-risk-card.png"});
 const conversationId=new URL(page.url()).searchParams.get("conversation");
 await page.reload();
 await expect(card).toBeVisible();
 const snapshot=await (await page.request.get(`/api/v1/ai/conversations/${conversationId}`)).json();
 const blocks=snapshot.messages.flatMap((message:{content_blocks:Array<{kind:string;content?:{score:string}}>})=>message.content_blocks);
 expect(blocks.filter((block:{kind:string})=>block.kind==="risk")).toHaveLength(1);
 const after=await (await page.request.get(`/api/v1/risks?task_id=${task.id}`)).json();
 expect(after.id).toBe(before.id);
 expect(after.judgment.score).toBe(before.judgment.score);
 expect((await (await page.request.get(`/api/v1/tasks/${task.id}`)).json()).version).toBe(task.version);
});
